import type {
  DashboardSectionId,
  StartupThemeId,
  ThemeExperience,
} from "@/lib/dna/types";
import type { ArtifactKind } from "@/lib/types/artifacts";

const baseKindLabels: Partial<Record<ArtifactKind, string>> = {
  "idea-brief": "Idea brief",
  "financial-projections": "Financial projections",
  "revenue-model": "Revenue model",
  "market-sizing": "Market sizing",
  "team-overview": "Team overview",
  "deal-structure": "Deal structure",
  "unit-economics": "Unit economics",
  "traction-kpis": "Traction KPIs",
  "competitive-landscape": "Competitive landscape",
  "gtm-plan": "Go-to-market",
  "burn-runway": "Burn & runway",
  milestones: "Milestones",
};

const baseSections: Record<DashboardSectionId, string> = {
  story: "Story",
  market: "Market & competition",
  economics: "Unit economics & revenue",
  financials: "Financials & runway",
  traction: "Traction & GTM",
  team: "Team & raise",
};

function experience(
  partial: Omit<ThemeExperience, "kindLabels" | "sectionTitles"> & {
    kindLabels?: ThemeExperience["kindLabels"];
    sectionTitles?: Partial<Record<DashboardSectionId, string>>;
  },
): ThemeExperience {
  return {
    ...partial,
    kindLabels: { ...baseKindLabels, ...partial.kindLabels },
    sectionTitles: { ...baseSections, ...partial.sectionTitles },
  };
}

export const THEME_CATALOG: Record<StartupThemeId, ThemeExperience> = {
  fashion: experience({
    id: "fashion",
    label: "Fashion",
    industryPhrase: "Fashion Commerce",
    welcomeLine: "Let's build the future of Fashion Commerce.",
    chatTitle: "Studio",
    dashboardTitle: "Fashion Command Center",
    dashboardSubtitle:
      "Designer growth, marketplace health, and creator traction — updated as you refine the brand.",
    navChat: "Chat",
    navDashboard: "Dashboard",
    advisorLabel: "Advisor",
    chatPlaceholder: "Ask about acquisition, pricing, or marketplace liquidity…",
    emptyChatTitle: "Let's build your Fashion Marketplace.",
    emptyChatBody:
      "Pressure-test brand positioning, designer supply, and what customers will actually pay for.",
    emptyDashboardTitle: "Your fashion workspace is ready.",
    emptyDashboardBody:
      "Generate the full investor pack — market, unit economics, traction, burn, and more.",
    generateCta: "Generate fashion docs",
    bootstrapRunning: "Building your fashion workspace documents…",
    bootstrapDone: "Fashion documents ready.",
    suggestions: [
      "Validate marketplace liquidity",
      "Find ideal commission %",
      "Designer acquisition strategy",
      "Pricing model for apparel",
    ],
    widgets: [
      { title: "Addressable fashion", hint: "SOM", slot: "som" },
      { title: "Year-1 commerce", hint: "Illustrative revenue", slot: "y1Revenue" },
      { title: "Creator LTV:CAC", hint: "Unit economics", slot: "ltvCac" },
      { title: "Runway", hint: "Months of oxygen", slot: "runway" },
    ],
    sectionTitles: {
      story: "Brand story",
      market: "Fashion market & rivals",
      economics: "Commerce economics",
      financials: "Projections & burn",
      traction: "Creator traction & GTM",
      team: "Studio team & raise",
    },
    kindLabels: {
      "idea-brief": "Brand brief",
      "revenue-model": "Commerce mix",
      "market-sizing": "Fashion TAM",
      "team-overview": "Studio team",
      "unit-economics": "Apparel unit economics",
      "traction-kpis": "Creator traction",
      "competitive-landscape": "Fashion rivals",
      "gtm-plan": "Acquisition mix",
    },
    icons: { spark: "✦", primary: "◎", secondary: "◈" },
    accent: {
      accent: "#a21caf",
      accentHover: "#c026d3",
      accentSubtle: "#fae8ff",
      accentDark: "#e879f9",
      accentHoverDark: "#f0abfc",
      accentSubtleDark: "#4a044e",
      gradientFrom: "#a21caf",
      gradientTo: "#db2777",
    },
    aiFocus:
      "Primary vertical: Fashion. Emphasize brand positioning, designer/creator supply, apparel unit economics, seasonal inventory risk, and marketplace liquidity when relevant.",
  }),

  fintech: experience({
    id: "fintech",
    label: "FinTech",
    industryPhrase: "FinTech",
    welcomeLine: "Ready to improve your FinTech startup today?",
    chatTitle: "War Room",
    dashboardTitle: "FinTech Control Deck",
    dashboardSubtitle:
      "Volume, activation, trust, and revenue — investor-grade views for financial products.",
    navChat: "Chat",
    navDashboard: "Dashboard",
    advisorLabel: "Advisor",
    chatPlaceholder: "Ask about compliance, pricing, or acquisition funnels…",
    emptyChatTitle: "Let's validate your FinTech business.",
    emptyChatBody:
      "Challenge unit economics, trust, and the path from first transaction to retention.",
    emptyDashboardTitle: "Your FinTech workspace is ready.",
    emptyDashboardBody:
      "Generate the full investor pack — TPV path, unit economics, burn, and compliance-ready framing.",
    generateCta: "Generate FinTech docs",
    bootstrapRunning: "Building your FinTech workspace documents…",
    bootstrapDone: "FinTech documents ready.",
    suggestions: [
      "Compliance checklist",
      "Revenue model stress-test",
      "Customer acquisition channels",
      "Pricing and take-rate",
    ],
    widgets: [
      { title: "Addressable finance", hint: "SOM", slot: "som" },
      { title: "Year-1 net take", hint: "Illustrative", slot: "y1Revenue" },
      { title: "LTV:CAC", hint: "Capital efficiency", slot: "ltvCac" },
      { title: "Runway", hint: "Months left", slot: "runway" },
    ],
    sectionTitles: {
      story: "Product story",
      market: "Finance market & rivals",
      economics: "Take-rate & unit economics",
      financials: "TPV path & burn",
      traction: "Activation & GTM",
      team: "Team & raise",
    },
    kindLabels: {
      "idea-brief": "Product brief",
      "financial-projections": "TPV projections",
      "revenue-model": "Take-rate model",
      "market-sizing": "Addressable finance",
      "unit-economics": "Txn unit economics",
      "traction-kpis": "Activation metrics",
      "burn-runway": "Burn & runway",
    },
    icons: { spark: "✦", primary: "◎", secondary: "◈" },
    accent: {
      accent: "#0369a1",
      accentHover: "#0284c7",
      accentSubtle: "#e0f2fe",
      accentDark: "#38bdf8",
      accentHoverDark: "#7dd3fc",
      accentSubtleDark: "#0c4a6e",
      gradientFrom: "#0369a1",
      gradientTo: "#06b6d4",
    },
    aiFocus:
      "Primary vertical: FinTech. Emphasize trust, compliance, unit economics per transaction, activation, and regulatory risk. Be concrete about INR flows when relevant.",
  }),

  education: experience({
    id: "education",
    label: "Education",
    industryPhrase: "Education",
    welcomeLine: "Let's grow what learners actually finish.",
    chatTitle: "Campus",
    dashboardTitle: "Learning Ops",
    dashboardSubtitle:
      "Enrollment, completion, course revenue, and retention — signals that matter in EdTech.",
    navChat: "Chat",
    navDashboard: "Dashboard",
    advisorLabel: "Advisor",
    chatPlaceholder: "Ask about course pricing, retention, or GTM…",
    emptyChatTitle: "Let's build your Education product.",
    emptyChatBody:
      "Pressure-test learning outcomes, pricing, and why students stay past week one.",
    emptyDashboardTitle: "Your EdTech workspace is ready.",
    emptyDashboardBody:
      "Generate the full investor pack — learner growth, completion, pricing, and burn.",
    generateCta: "Generate EdTech docs",
    bootstrapRunning: "Building your education workspace documents…",
    bootstrapDone: "Education documents ready.",
    suggestions: [
      "Course pricing strategy",
      "Retention ideas",
      "Go-to-market for learners",
      "Completion rate levers",
    ],
    widgets: [
      { title: "Learner SOM", hint: "Obtainable market", slot: "som" },
      { title: "Year-1 course revenue", hint: "Illustrative", slot: "y1Revenue" },
      { title: "LTV:CAC", hint: "Cohort economics", slot: "ltvCac" },
      { title: "Runway", hint: "Months left", slot: "runway" },
    ],
    sectionTitles: {
      story: "Learning story",
      market: "Learner market & rivals",
      economics: "Course economics",
      financials: "Revenue path & burn",
      traction: "Enrollment & GTM",
      team: "Faculty & raise",
    },
    kindLabels: {
      "idea-brief": "Learning brief",
      "revenue-model": "Course monetization",
      "market-sizing": "Learner TAM",
      "team-overview": "Faculty & ops",
      "traction-kpis": "Student growth",
      "unit-economics": "Cohort unit economics",
    },
    icons: { spark: "✦", primary: "◎", secondary: "◈" },
    accent: {
      accent: "#c2410c",
      accentHover: "#ea580c",
      accentSubtle: "#ffedd5",
      accentDark: "#fb923c",
      accentHoverDark: "#fdba74",
      accentSubtleDark: "#7c2d12",
      gradientFrom: "#ea580c",
      gradientTo: "#f59e0b",
    },
    aiFocus:
      "Primary vertical: Education / EdTech. Emphasize learning outcomes, completion, pricing packs, acquisition CAC for students, and retention after purchase.",
  }),

  food: experience({
    id: "food",
    label: "Food",
    industryPhrase: "Food & Hospitality",
    welcomeLine: "Let's make Food & Hospitality work unit by unit.",
    chatTitle: "Kitchen",
    dashboardTitle: "Kitchen Board",
    dashboardSubtitle:
      "Orders, capacity, repeats, and delivery reach — ops metrics for food businesses.",
    navChat: "Chat",
    navDashboard: "Dashboard",
    advisorLabel: "Advisor",
    chatPlaceholder: "Ask about unit economics, delivery, or repeat rates…",
    emptyChatTitle: "Let's build your Food business.",
    emptyChatBody:
      "Challenge margins, kitchen capacity, and what keeps customers ordering again.",
    emptyDashboardTitle: "Your food workspace is ready.",
    emptyDashboardBody:
      "Generate the full investor pack — orders path, margins, burn, and GTM.",
    generateCta: "Generate food docs",
    bootstrapRunning: "Building your food workspace documents…",
    bootstrapDone: "Food documents ready.",
    suggestions: [
      "Order economics",
      "Kitchen capacity plan",
      "Repeat customer loops",
      "Delivery radius strategy",
    ],
    widgets: [
      { title: "Local SOM", hint: "Obtainable demand", slot: "som" },
      { title: "Year-1 GMV path", hint: "Illustrative", slot: "y1Revenue" },
      { title: "Order LTV:CAC", hint: "Unit economics", slot: "ltvCac" },
      { title: "Runway", hint: "Months left", slot: "runway" },
    ],
    sectionTitles: {
      story: "Concept story",
      market: "Local demand & rivals",
      economics: "Order economics",
      financials: "Projections & burn",
      traction: "Orders & GTM",
      team: "Kitchen team & raise",
    },
    kindLabels: {
      "idea-brief": "Concept brief",
      "revenue-model": "Menu & channels",
      "market-sizing": "Local demand",
      "team-overview": "Kitchen team",
      "unit-economics": "Order unit economics",
      "traction-kpis": "Order traction",
    },
    icons: { spark: "✦", primary: "◎", secondary: "◈" },
    accent: {
      accent: "#b45309",
      accentHover: "#d97706",
      accentSubtle: "#fef3c7",
      accentDark: "#fbbf24",
      accentHoverDark: "#fcd34d",
      accentSubtleDark: "#78350f",
      gradientFrom: "#b45309",
      gradientTo: "#dc2626",
    },
    aiFocus:
      "Primary vertical: Food / hospitality. Emphasize contribution margin per order, kitchen capacity, delivery CAC, and repeat purchase behavior.",
  }),

  health: experience({
    id: "health",
    label: "Healthcare",
    industryPhrase: "Healthcare",
    welcomeLine: "Let's build Healthcare that patients and providers trust.",
    chatTitle: "Clinic",
    dashboardTitle: "Care Ops",
    dashboardSubtitle:
      "Patient growth, trust, utilization, and outcomes — signals for health startups.",
    navChat: "Chat",
    navDashboard: "Dashboard",
    advisorLabel: "Advisor",
    chatPlaceholder: "Ask about trust, adoption, or provider workflows…",
    emptyChatTitle: "Let's validate your Healthcare startup.",
    emptyChatBody:
      "Pressure-test clinical trust, adoption, and who actually pays for care.",
    emptyDashboardTitle: "Your healthcare workspace is ready.",
    emptyDashboardBody:
      "Generate the full investor pack — patient TAM, unit economics, burn, and GTM.",
    generateCta: "Generate health docs",
    bootstrapRunning: "Building your healthcare workspace documents…",
    bootstrapDone: "Healthcare documents ready.",
    suggestions: [
      "Trust & compliance checklist",
      "Provider acquisition",
      "Patient retention",
      "Who pays — payer map",
    ],
    widgets: [
      { title: "Patient SOM", hint: "Obtainable", slot: "som" },
      { title: "Year-1 care revenue", hint: "Illustrative", slot: "y1Revenue" },
      { title: "LTV:CAC", hint: "Care economics", slot: "ltvCac" },
      { title: "Runway", hint: "Months left", slot: "runway" },
    ],
    sectionTitles: {
      story: "Care story",
      market: "Patient market & rivals",
      economics: "Care economics",
      financials: "Projections & burn",
      traction: "Utilization & GTM",
      team: "Clinical team & raise",
    },
    kindLabels: {
      "idea-brief": "Care brief",
      "revenue-model": "Care monetization",
      "market-sizing": "Patient TAM",
      "team-overview": "Clinical team",
      "unit-economics": "Care unit economics",
    },
    icons: { spark: "✦", primary: "◎", secondary: "◈" },
    accent: {
      accent: "#047857",
      accentHover: "#059669",
      accentSubtle: "#d1fae5",
      accentDark: "#34d399",
      accentHoverDark: "#6ee7b7",
      accentSubtleDark: "#064e3b",
      gradientFrom: "#047857",
      gradientTo: "#0d9488",
    },
    aiFocus:
      "Primary vertical: Healthcare. Emphasize trust, clinical/ops adoption, who pays (patient vs insurer vs provider), and regulatory caution without fear-mongering.",
  }),

  ai: experience({
    id: "ai",
    label: "AI",
    industryPhrase: "AI Products",
    welcomeLine: "Let's ship AI Products people actually keep using.",
    chatTitle: "Lab",
    dashboardTitle: "Model Ops",
    dashboardSubtitle:
      "Usage, retention, automation ROI, and moat — what investors probe in AI.",
    navChat: "Chat",
    navDashboard: "Dashboard",
    advisorLabel: "Advisor",
    chatPlaceholder: "Ask about moat, usage, or automation ROI…",
    emptyChatTitle: "Let's build your AI product.",
    emptyChatBody:
      "Challenge differentiation, evals, and whether usage turns into paid retention.",
    emptyDashboardTitle: "Your AI workspace is ready.",
    emptyDashboardBody:
      "Generate the full investor pack — usage path, unit economics, burn, and GTM.",
    generateCta: "Generate AI docs",
    bootstrapRunning: "Building your AI workspace documents…",
    bootstrapDone: "AI documents ready.",
    suggestions: [
      "Moat vs wrappers",
      "Usage → revenue path",
      "Eval & quality plan",
      "Enterprise GTM",
    ],
    widgets: [
      { title: "AI spend SOM", hint: "Obtainable", slot: "som" },
      { title: "Year-1 ARR path", hint: "Illustrative", slot: "y1Revenue" },
      { title: "LTV:CAC", hint: "SaaS-like economics", slot: "ltvCac" },
      { title: "Runway", hint: "Months left", slot: "runway" },
    ],
    sectionTitles: {
      story: "Product story",
      market: "AI market & rivals",
      economics: "Usage economics",
      financials: "Projections & burn",
      traction: "Usage & GTM",
      team: "Team & raise",
    },
    kindLabels: {
      "idea-brief": "Product brief",
      "revenue-model": "Usage monetization",
      "market-sizing": "AI spend TAM",
      "traction-kpis": "Active usage",
      "unit-economics": "Usage unit economics",
    },
    icons: { spark: "✦", primary: "◎", secondary: "◈" },
    accent: {
      accent: "#4f46e5",
      accentHover: "#6366f1",
      accentSubtle: "#e0e7ff",
      accentDark: "#818cf8",
      accentHoverDark: "#a5b4fc",
      accentSubtleDark: "#312e81",
      gradientFrom: "#4f46e5",
      gradientTo: "#7c3aed",
    },
    aiFocus:
      "Primary vertical: AI products. Emphasize differentiation vs wrappers, evaluation quality, usage retention, data/workflow moat, and realistic cost of inference.",
  }),

  travel: experience({
    id: "travel",
    label: "Travel",
    industryPhrase: "Travel",
    welcomeLine: "Let's build Travel experiences people book twice.",
    chatTitle: "Desk",
    dashboardTitle: "Travel Board",
    dashboardSubtitle:
      "Bookings, repeat trips, partner supply, and seasonality — travel-native metrics.",
    navChat: "Chat",
    navDashboard: "Dashboard",
    advisorLabel: "Advisor",
    chatPlaceholder: "Ask about bookings, partners, or seasonality…",
    emptyChatTitle: "Let's build your Travel startup.",
    emptyChatBody:
      "Pressure-test demand seasonality, partner supply, and booking conversion.",
    emptyDashboardTitle: "Your travel workspace is ready.",
    emptyDashboardBody:
      "Generate the full investor pack — bookings path, unit economics, burn, and GTM.",
    generateCta: "Generate travel docs",
    bootstrapRunning: "Building your travel workspace documents…",
    bootstrapDone: "Travel documents ready.",
    suggestions: [
      "Booking conversion",
      "Partner supply strategy",
      "Seasonality plan",
      "Repeat traveler loops",
    ],
    widgets: [
      { title: "Travel SOM", hint: "Obtainable", slot: "som" },
      { title: "Year-1 bookings", hint: "Illustrative", slot: "y1Revenue" },
      { title: "LTV:CAC", hint: "Trip economics", slot: "ltvCac" },
      { title: "Runway", hint: "Months left", slot: "runway" },
    ],
    sectionTitles: {
      story: "Trip story",
      market: "Travel market & rivals",
      economics: "Booking economics",
      financials: "Projections & burn",
      traction: "Bookings & GTM",
      team: "Team & raise",
    },
    kindLabels: {
      "idea-brief": "Trip brief",
      "revenue-model": "Booking mix",
      "market-sizing": "Travel TAM",
      "traction-kpis": "Booking traction",
    },
    icons: { spark: "✦", primary: "◎", secondary: "◈" },
    accent: {
      accent: "#0e7490",
      accentHover: "#0891b2",
      accentSubtle: "#cffafe",
      accentDark: "#22d3ee",
      accentHoverDark: "#67e8f9",
      accentSubtleDark: "#164e63",
      gradientFrom: "#0e7490",
      gradientTo: "#2563eb",
    },
    aiFocus:
      "Primary vertical: Travel. Emphasize seasonality, partner supply, booking conversion, and repeat travel behavior.",
  }),

  saas: experience({
    id: "saas",
    label: "SaaS",
    industryPhrase: "B2B SaaS",
    welcomeLine: "Let's sharpen your B2B SaaS story.",
    chatTitle: "Workspace",
    dashboardTitle: "SaaS Command",
    dashboardSubtitle:
      "MRR path, activation, retention, and pipeline — classic SaaS investor views.",
    navChat: "Chat",
    navDashboard: "Dashboard",
    advisorLabel: "Advisor",
    chatPlaceholder: "Ask about activation, pricing, or retention…",
    emptyChatTitle: "Let's build your SaaS product.",
    emptyChatBody:
      "Challenge activation, willingness-to-pay, and the wedge that expands seats.",
    emptyDashboardTitle: "Your SaaS workspace is ready.",
    emptyDashboardBody:
      "Generate the full investor pack — MRR path, unit economics, burn, and GTM.",
    generateCta: "Generate SaaS docs",
    bootstrapRunning: "Building your SaaS workspace documents…",
    bootstrapDone: "SaaS documents ready.",
    suggestions: [
      "Pricing & packaging",
      "Activation checklist",
      "Retention levers",
      "Expansion revenue",
    ],
    widgets: [
      { title: "SaaS SOM", hint: "Obtainable", slot: "som" },
      { title: "Year-1 ARR path", hint: "Illustrative", slot: "y1Revenue" },
      { title: "LTV:CAC", hint: "SaaS classic", slot: "ltvCac" },
      { title: "Runway", hint: "Months left", slot: "runway" },
    ],
    sectionTitles: {
      story: "Product story",
      market: "SaaS market & rivals",
      economics: "Subscription economics",
      financials: "MRR path & burn",
      traction: "Activation & GTM",
      team: "Team & raise",
    },
    kindLabels: {
      "idea-brief": "Product brief",
      "financial-projections": "MRR projections",
      "revenue-model": "Subscription mix",
      "unit-economics": "SaaS unit economics",
      "traction-kpis": "Activation metrics",
    },
    icons: { spark: "✦", primary: "◎", secondary: "◈" },
    accent: {
      accent: "#0f766e",
      accentHover: "#0d9488",
      accentSubtle: "#ccfbf1",
      accentDark: "#14b8a6",
      accentHoverDark: "#2dd4bf",
      accentSubtleDark: "#134e4a",
      gradientFrom: "#0f766e",
      gradientTo: "#2563eb",
    },
    aiFocus:
      "Primary vertical: B2B SaaS. Emphasize activation, retention, pricing/packaging, seat expansion, and credible pipeline — not vanity TAM.",
  }),

  marketplace: experience({
    id: "marketplace",
    label: "Marketplace",
    industryPhrase: "Marketplace",
    welcomeLine: "Let's balance both sides of your Marketplace.",
    chatTitle: "Exchange",
    dashboardTitle: "Marketplace Pulse",
    dashboardSubtitle:
      "Liquidity, take rate, supply density, and GMV — two-sided health in one view.",
    navChat: "Chat",
    navDashboard: "Dashboard",
    advisorLabel: "Advisor",
    chatPlaceholder: "Ask about liquidity, take rate, or supply…",
    emptyChatTitle: "Let's build your Marketplace.",
    emptyChatBody:
      "Pressure-test chicken-and-egg, take rate, and which side you win first.",
    emptyDashboardTitle: "Your marketplace workspace is ready.",
    emptyDashboardBody:
      "Generate the full investor pack — GMV path, take rate, burn, and liquidity GTM.",
    generateCta: "Generate marketplace docs",
    bootstrapRunning: "Building your marketplace workspace documents…",
    bootstrapDone: "Marketplace documents ready.",
    suggestions: [
      "Liquidity playbook",
      "Ideal take rate",
      "Supply acquisition",
      "Demand-side GTM",
    ],
    widgets: [
      { title: "GMV SOM", hint: "Obtainable", slot: "som" },
      { title: "Year-1 GMV path", hint: "Illustrative", slot: "y1Revenue" },
      { title: "LTV:CAC", hint: "Two-sided CAC", slot: "ltvCac" },
      { title: "Runway", hint: "Months left", slot: "runway" },
    ],
    sectionTitles: {
      story: "Marketplace story",
      market: "Category & rivals",
      economics: "Take-rate economics",
      financials: "GMV path & burn",
      traction: "Liquidity & GTM",
      team: "Team & raise",
    },
    kindLabels: {
      "idea-brief": "Marketplace brief",
      "revenue-model": "Take-rate model",
      "market-sizing": "GMV opportunity",
      "unit-economics": "Marketplace unit economics",
      "traction-kpis": "Liquidity metrics",
      "gtm-plan": "Supply & demand GTM",
    },
    icons: { spark: "✦", primary: "◎", secondary: "◈" },
    accent: {
      accent: "#7c3aed",
      accentHover: "#8b5cf6",
      accentSubtle: "#ede9fe",
      accentDark: "#a78bfa",
      accentHoverDark: "#c4b5fd",
      accentSubtleDark: "#4c1d95",
      gradientFrom: "#7c3aed",
      gradientTo: "#db2777",
    },
    aiFocus:
      "Primary vertical: Marketplace. Emphasize two-sided liquidity, which side to win first, take rate, and concentration risk on supply or demand.",
  }),

  general: experience({
    id: "general",
    label: "Startup",
    industryPhrase: "your startup",
    welcomeLine: "Ready to pressure-test your startup today?",
    chatTitle: "Chat",
    dashboardTitle: "Investor workspace",
    dashboardSubtitle:
      "Story, market, economics, financials, traction, and raise — generated from onboarding, then refined in chat.",
    navChat: "Chat",
    navDashboard: "Dashboard",
    advisorLabel: "Advisor",
    chatPlaceholder: "Answer the challenge — or push back with evidence…",
    emptyChatTitle: "Let's build your startup workspace.",
    emptyChatBody:
      "Challenge assumptions, sharpen the story, and prepare for real investor questions.",
    emptyDashboardTitle: "Your investor pack is ready to generate.",
    emptyDashboardBody:
      "Create the full set: market, unit economics, traction, burn, GTM, milestones, and more.",
    generateCta: "Generate investor docs",
    bootstrapRunning: "Building your investor documents…",
    bootstrapDone: "Investor documents ready.",
    suggestions: [
      "Pressure-test the idea",
      "Clarify who pays",
      "Map go-to-market",
      "Unit economics sketch",
    ],
    widgets: [
      { title: "SOM", hint: "Obtainable market", slot: "som" },
      { title: "Year-1 revenue", hint: "Illustrative", slot: "y1Revenue" },
      { title: "LTV:CAC", hint: "Unit economics", slot: "ltvCac" },
      { title: "Runway", hint: "Months left", slot: "runway" },
    ],
    icons: { spark: "✦", primary: "◎", secondary: "◈" },
    accent: {
      accent: "#0f766e",
      accentHover: "#0d9488",
      accentSubtle: "#ccfbf1",
      accentDark: "#14b8a6",
      accentHoverDark: "#2dd4bf",
      accentSubtleDark: "#134e4a",
      gradientFrom: "#0f766e",
      gradientTo: "#0d9488",
    },
    aiFocus:
      "Vertical not strongly identified. Infer industry carefully from founder answers and stay concrete about who pays and why now.",
  }),
};

export function getThemeExperience(theme: StartupThemeId): ThemeExperience {
  return THEME_CATALOG[theme] ?? THEME_CATALOG.general;
}
