import type { StartupThemeId } from "@/lib/dna/types";

/** Keyword dictionaries for lightweight theme scoring. */
export const THEME_KEYWORDS: Record<
  Exclude<StartupThemeId, "general">,
  string[]
> = {
  health: [
    "hospital",
    "doctor",
    "clinic",
    "patient",
    "medical",
    "health",
    "healthcare",
    "pharmacy",
    "wellness",
    "therapy",
    "diagnostic",
    "nurse",
    "telemedicine",
    "mental health",
    "fitness",
    "medico",
  ],
  fintech: [
    "bank",
    "banking",
    "payment",
    "payments",
    "upi",
    "wallet",
    "finance",
    "financial",
    "loan",
    "credit",
    "investment",
    "invest",
    "fintech",
    "insurance",
    "lending",
    "neobank",
    "kyc",
    "rupee",
    "inr",
    "transaction",
  ],
  education: [
    "student",
    "teacher",
    "learning",
    "course",
    "school",
    "college",
    "exam",
    "education",
    "edtech",
    "tutor",
    "classroom",
    "curriculum",
    "coaching",
    "university",
    "lesson",
  ],
  fashion: [
    "fashion",
    "designer",
    "clothing",
    "apparel",
    "boutique",
    "garment",
    "stylist",
    "model",
    "models",
    "wear",
    "wardrobe",
    "textile",
    "couture",
    "runway",
    "outfit",
    "dress",
    "style",
  ],
  food: [
    "restaurant",
    "food",
    "kitchen",
    "delivery",
    "chef",
    "recipe",
    "cafe",
    "café",
    "dining",
    "meal",
    "grocery",
    "catering",
    "cloud kitchen",
    "qsr",
    "cuisine",
  ],
  ai: [
    " ai ",
    "llm",
    "gpt",
    "machine learning",
    "ml model",
    "automation",
    "assistant",
    "generative",
    "neural",
    "chatgpt",
    "openai",
    "agentic",
    "computer vision",
    "nlp",
  ],
  travel: [
    "travel",
    "trip",
    "booking",
    "hotel",
    "flight",
    "vacation",
    "tourism",
    "itinerary",
    "airline",
    "hostel",
    "staycation",
    "destination",
  ],
  saas: [
    "subscription",
    "software",
    "dashboard",
    "b2b",
    "crm",
    "workflow",
    "saas",
    "platform",
    "productivity",
    "api",
    "cloud software",
    "enterprise",
    "ops tool",
  ],
  marketplace: [
    "buyers",
    "sellers",
    "vendors",
    "marketplace",
    "commission",
    "two-sided",
    "two sided",
    "multi-vendor",
    "listings",
    "take rate",
    "supply side",
    "demand side",
  ],
};

/** Direct boosts from explicit business-model cards. */
export const BUSINESS_MODEL_BOOSTS: Record<string, Partial<Record<StartupThemeId, number>>> = {
  "SaaS subscription": { saas: 4 },
  Marketplace: { marketplace: 5 },
  "Transaction fee": { fintech: 2, marketplace: 2 },
  "Services / agency": { saas: 1 },
  "Hardware + software": { saas: 1, ai: 1 },
};
